# Generated by Django 4.2.19 on 2025-04-12 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autoservice',
            name='address',
            field=models.TextField(verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='autoservice',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название автосервиса'),
        ),
        migrations.AlterField(
            model_name='autoservice',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Номер для связи'),
        ),
    ]
