# Generated by Django 4.2.19 on 2025-04-19 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_autoservice_address_alter_autoservice_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_customer',
            field=models.BooleanField(default=True, verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_service',
            field=models.BooleanField(default=False, verbose_name='Автосервис'),
        ),
    ]
