# Generated by Django 4.2.21 on 2025-05-18 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_user_is_customer_alter_user_is_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_customer',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_service',
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Администратор'), ('manager', 'Менеджер'), ('customer', 'Клиент'), ('service', 'Автосервис')], default='customer', max_length=20),
        ),
    ]
