# Generated by Django 4.2.19 on 2025-05-11 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repairs', '0003_alter_repairresponse_options_and_more'),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'ordering': ['timestamp']},
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='chat_room',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='repair_request',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='repairs.repairrequest'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='response',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='repairs.repairresponse'),
        ),
        migrations.DeleteModel(
            name='ChatRoom',
        ),
    ]
