# Generated by Django 4.2.19 on 2025-04-28 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repairs', '0003_alter_repairresponse_options_and_more'),
        ('chat', '0003_alter_chatmessage_options_chatmessage_repair_request'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'ordering': ['timestamp']},
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='response',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='repairs.repairresponse'),
        ),
    ]
