# Generated by Django 4.2.19 on 2025-04-13 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0003_alter_car_options_alter_car_brand_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='garage',
            options={'ordering': ['name'], 'verbose_name': 'Автосервис', 'verbose_name_plural': 'Автосервисы'},
        ),
        migrations.AddField(
            model_name='garage',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='garage',
            name='specialization',
            field=models.CharField(blank=True, max_length=100, verbose_name='Специализация'),
        ),
        migrations.AlterField(
            model_name='garage',
            name='address',
            field=models.TextField(blank=True, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='garage',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название автосервиса'),
        ),
    ]
