# Generated by Django 4.2.19 on 2025-04-13 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0004_alter_garage_options_garage_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerecord',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='garage.car'),
        ),
        migrations.AlterField(
            model_name='servicerecord',
            name='garage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='garage.garage'),
        ),
    ]
