# Generated by Django 4.2.19 on 2025-04-13 17:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('garage', '0006_servicerecord_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerecord',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='servicerecord',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Создатель записи'),
        ),
        migrations.AlterField(
            model_name='servicerecord',
            name='receipt',
            field=models.FileField(blank=True, upload_to='service_receipts/', verbose_name='фото чека(не обязательно)'),
        ),
        migrations.AlterField(
            model_name='servicerecord',
            name='service_type',
            field=models.CharField(max_length=100, verbose_name='Вид работ'),
        ),
    ]
