# Generated by Django 4.2.19 on 2025-05-16 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_user_is_customer_alter_user_is_service'),
        ('garage', '0007_alter_servicerecord_cost_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicerecord',
            name='garage',
        ),
        migrations.AddField(
            model_name='servicerecord',
            name='autoservice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.autoservice'),
        ),
    ]
