# Generated by Django 4.2.21 on 2025-06-22 14:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0011_car_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'verbose_name': 'Автомобиль', 'verbose_name_plural': 'Автомобили'},
        ),
        migrations.RemoveField(
            model_name='car',
            name='body_type',
        ),
        migrations.RemoveField(
            model_name='car',
            name='engine_type',
        ),
        migrations.RemoveField(
            model_name='car',
            name='engine_volume',
        ),
        migrations.AddField(
            model_name='car',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата добавления'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='car',
            name='brand',
            field=models.CharField(choices=[('Toyota', 'Toyota'), ('Honda', 'Honda'), ('BMW', 'BMW'), ('Mercedes-Benz', 'Mercedes-Benz'), ('Audi', 'Audi'), ('Volkswagen', 'Volkswagen'), ('Ford', 'Ford'), ('Chevrolet', 'Chevrolet'), ('Nissan', 'Nissan'), ('Hyundai', 'Hyundai'), ('Kia', 'Kia'), ('Subaru', 'Subaru'), ('Mazda', 'Mazda'), ('Lexus', 'Lexus'), ('Volvo', 'Volvo'), ('Jeep', 'Jeep'), ('Tesla', 'Tesla'), ('Porsche', 'Porsche'), ('Land Rover', 'Land Rover'), ('Jaguar', 'Jaguar'), ('Mitsubishi', 'Mitsubishi'), ('Fiat', 'Fiat'), ('Peugeot', 'Peugeot'), ('Renault', 'Renault'), ('Citroën', 'Citroën'), ('Skoda', 'Skoda'), ('Seat', 'Seat'), ('Opel', 'Opel'), ('Suzuki', 'Suzuki'), ('Dacia', 'Dacia'), ('Alfa Romeo', 'Alfa Romeo'), ('Chrysler', 'Chrysler'), ('Dodge', 'Dodge'), ('Infiniti', 'Infiniti'), ('Acura', 'Acura'), ('Buick', 'Buick'), ('Cadillac', 'Cadillac'), ('GMC', 'GMC'), ('Lincoln', 'Lincoln'), ('Mini', 'Mini'), ('Smart', 'Smart'), ('Ferrari', 'Ferrari'), ('Lamborghini', 'Lamborghini'), ('Maserati', 'Maserati'), ('Bentley', 'Bentley'), ('Rolls-Royce', 'Rolls-Royce'), ('Aston Martin', 'Aston Martin'), ('McLaren', 'McLaren'), ('Bugatti', 'Bugatti'), ('Lada', 'Lada'), ('Geely', 'Geely'), ('BYD', 'BYD'), ('Great Wall', 'Great Wall'), ('Chery', 'Chery'), ('Haval', 'Haval'), ('Genesis', 'Genesis'), ('Rivian', 'Rivian'), ('Lucid', 'Lucid')], max_length=50, verbose_name='Марка автомобиля'),
        ),
        migrations.AlterField(
            model_name='car',
            name='mileage',
            field=models.PositiveIntegerField(default=0, verbose_name='Пробег (км)'),
        ),
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.CharField(max_length=50, verbose_name='Модель автомобиля'),
        ),
        migrations.AlterField(
            model_name='car',
            name='vin',
            field=models.CharField(blank=True, max_length=17, null=True, unique=True, verbose_name='VIN-номер'),
        ),
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.PositiveIntegerField(choices=[(2025, 2025), (2024, 2024), (2023, 2023), (2022, 2022), (2021, 2021), (2020, 2020), (2019, 2019), (2018, 2018), (2017, 2017), (2016, 2016), (2015, 2015), (2014, 2014), (2013, 2013), (2012, 2012), (2011, 2011), (2010, 2010), (2009, 2009), (2008, 2008), (2007, 2007), (2006, 2006), (2005, 2005), (2004, 2004), (2003, 2003), (2002, 2002), (2001, 2001), (2000, 2000), (1999, 1999), (1998, 1998), (1997, 1997), (1996, 1996)], verbose_name='Год выпуска'),
        ),
    ]
