# Generated by Django 4.2.21 on 2025-06-29 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0012_alter_car_options_remove_car_body_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='car',
            name='model',
        ),
        migrations.RemoveField(
            model_name='car',
            name='year',
        ),
        migrations.CreateModel(
            name='CarBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50, verbose_name='Марка')),
                ('model', models.CharField(max_length=50, verbose_name='Модель')),
                ('year', models.PositiveIntegerField(verbose_name='Год выпуска')),
                ('engine_type', models.CharField(choices=[('petrol', 'Бензин'), ('diesel', 'Дизель'), ('hybrid', 'Гибрид'), ('electric', 'Электро')], max_length=20, verbose_name='Тип двигателя')),
                ('engine_volume', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='Объем двигателя (л)')),
            ],
            options={
                'verbose_name': 'Авто из базы',
                'verbose_name_plural': 'База автомобилей',
                'unique_together': {('brand', 'model', 'year', 'engine_type', 'engine_volume')},
            },
        ),
        migrations.AddField(
            model_name='car',
            name='base_car',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='garage.carbase', verbose_name='Автомобиль из базы'),
        ),
    ]
