# Generated by Django 4.2.21 on 2025-06-29 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0013_remove_car_brand_remove_car_model_remove_car_year_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='carbase',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='carbase',
            name='year_from',
            field=models.PositiveIntegerField(default=2000, verbose_name='Год начала выпуска'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carbase',
            name='year_to',
            field=models.PositiveIntegerField(default=2025, verbose_name='Год окончания выпуска'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='carbase',
            unique_together={('brand', 'model', 'year_from', 'year_to', 'engine_type', 'engine_volume')},
        ),
        migrations.RemoveField(
            model_name='carbase',
            name='year',
        ),
    ]
