# Generated by Django 4.2.21 on 2025-06-30 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0015_car_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carbase',
            name='engine_volume',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Объем двигателя (л)'),
        ),
    ]
