# Generated by Django 4.2.21 on 2025-06-30 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0016_alter_carbase_engine_volume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carbase',
            name='year_to',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Год окончания выпуска'),
        ),
    ]
