# Generated by Django 4.2.21 on 2025-06-30 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0017_alter_carbase_year_to'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='carbase',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='carbase',
            name='generation',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Поколение'),
        ),
        migrations.AlterUniqueTogether(
            name='carbase',
            unique_together={('brand', 'model', 'generation', 'year_from', 'year_to', 'engine_type', 'engine_volume')},
        ),
    ]
