# Generated by Django 4.2.21 on 2025-07-04 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0018_alter_carbase_unique_together_carbase_generation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carbase',
            name='engine_type',
            field=models.CharField(blank=True, choices=[('petrol', 'Бензин'), ('diesel', 'Дизель'), ('hybrid', 'Гибрид'), ('electric', 'Электро')], max_length=20, null=True, verbose_name='Тип двигателя'),
        ),
    ]
