# Generated by Django 4.2.21 on 2025-07-04 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0019_alter_carbase_engine_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='mileage',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Пробег (км)'),
        ),
    ]
