# Generated by Django 4.2.21 on 2025-07-04 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0020_alter_car_mileage'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='engine_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='engine_volume',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
    ]
