# Generated by Django 4.2.19 on 2025-05-16 13:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repairs', '0004_repairrequest_executor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reviews', '0002_review_request_review_service_review_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='repairs.repairrequest', verbose_name='Заявка'),
        ),
        migrations.AlterField(
            model_name='review',
            name='service',
            field=models.ForeignKey(limit_choices_to={'is_service': True}, on_delete=django.db.models.deletion.CASCADE, related_name='reviews_received', to=settings.AUTH_USER_MODEL, verbose_name='Сервис'),
        ),
    ]
