# Generated by Django 4.2.19 on 2025-03-30 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('garage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('proposed_date', models.DateTimeField()),
                ('is_accepted', models.BooleanField(default=False)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='garage.servicerequest')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.autoservice')),
            ],
        ),
    ]
