# Generated by Django 4.2.19 on 2025-04-14 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ServiceOffer',
        ),
    ]
