# Generated by Django 4.2.19 on 2025-05-14 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0004_user_is_customer_alter_user_is_service'),
        ('services', '0002_delete_serviceoffer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('autoservice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='account.autoservice')),
            ],
        ),
    ]
