# Generated by Django 4.2.19 on 2025-05-14 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='description',
        ),
    ]
