# Generated by Django 4.2.19 on 2025-05-15 18:25

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_remove_booking_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='date_time',
        ),
        migrations.AddField(
            model_name='booking',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='booking',
            name='time',
            field=models.TimeField(default=datetime.time(9, 0)),
        ),
    ]
