# Generated by Django 4.2.19 on 2025-05-15 19:33

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_remove_booking_date_time_booking_date_booking_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workinghours',
            name='day_of_week',
        ),
        migrations.AddField(
            model_name='workinghours',
            name='days_of_week',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Пн', 'Понедельник'), ('Вт', 'Вторник'), ('Ср', 'Среда'), ('Чт', 'Четверг'), ('Пт', 'Пятница'), ('Сб', 'Суббота'), ('Вс', 'Воскресенье')], default=['mon'], max_length=20),
        ),
        migrations.AlterField(
            model_name='workinghours',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='workinghours',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
