# Generated by Django 4.2.19 on 2025-05-15 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_remove_workinghours_day_of_week_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workinghours',
            name='autoservice',
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.DeleteModel(
            name='WorkingHours',
        ),
    ]
