# Generated by Django 4.2.19 on 2025-05-16 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_master'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master',
            name='experience',
            field=models.PositiveIntegerField(default=0, verbose_name='Стаж'),
        ),
        migrations.AlterField(
            model_name='master',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='master',
            name='specialization',
            field=models.CharField(max_length=200, verbose_name='Специализация'),
        ),
    ]
