# Generated by Django 4.2.21 on 2025-06-15 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_autoservice_description'),
        ('services', '0011_alter_master_experience_alter_master_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoServicePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='service_photos/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('autoservice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='account.autoservice')),
            ],
        ),
    ]
